### ISSUE TITLE
Is it possible to add raw input to this dll

### ISSUE THREAD

**Issue by tooopee** [JohnnyonFlame/DInputWrapper#6]
I'm a total directx noob, is it possible to remove mouse acceleration from the original Metro 2033 with this fix? It would be so great

**Comment by JohnnyonFlame** [comment]
It is possible to add rawinput. If that would solve the mouse acceleration issue I'd have to investigate. I still want to investigate some more throughout fixes for Metro but that'll have to wait until I buy the Redux games from GOG.

**Comment by tooopee** [comment]
I'm so glad to hear that! Thank you for your support and attention for Metro series!
